[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.dev"

[deploy]
startCommand = "nginx && pnpm run pm2"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
