[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.dev"

[deploy]
startCommand = "sh -c 'export PORT=5000 && nginx && pnpm run pm2'"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
